---
development:
  cloud_name: dprgv95ht
  api_key: '656735182639465'
  api_secret: hwYr8T_gH2wQE6Oh_wKVA6pC4gg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dprgv95ht
  api_key: '656735182639465'
  api_secret: hwYr8T_gH2wQE6Oh_wKVA6pC4gg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dprgv95ht
  api_key: '656735182639465'
  api_secret: hwYr8T_gH2wQE6Oh_wKVA6pC4gg
  enhance_image_tag: true
  static_file_support: false
